


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM users WHERE auth_id = auth.uid() AND role = 'Admin'
  );
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_avg_rating"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  UPDATE providers
  SET average_rating = (
    SELECT COALESCE(ROUND(AVG(stars), 2), 0.00)
    FROM ratings
    WHERE provider_id = NEW.provider_id
  )
  WHERE provider_id = NEW.provider_id;
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_avg_rating"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admins" (
    "admin_id" bigint NOT NULL,
    "user_id" bigint,
    "office" character varying(100) DEFAULT 'PESO'::character varying NOT NULL,
    "position" character varying(100)
);


ALTER TABLE "public"."admins" OWNER TO "postgres";


ALTER TABLE "public"."admins" ALTER COLUMN "admin_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admins_admin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessment_answers" (
    "answer_id" bigint NOT NULL,
    "attempt_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "chosen_choice_id" bigint
);


ALTER TABLE "public"."assessment_answers" OWNER TO "postgres";


ALTER TABLE "public"."assessment_answers" ALTER COLUMN "answer_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessment_answers_answer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessment_attempts" (
    "attempt_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "test_id" bigint NOT NULL,
    "score_raw" numeric(5,2),
    "score_pct" numeric(5,2),
    "passed" boolean,
    "started_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "submitted_at" timestamp with time zone
);


ALTER TABLE "public"."assessment_attempts" OWNER TO "postgres";


ALTER TABLE "public"."assessment_attempts" ALTER COLUMN "attempt_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessment_attempts_attempt_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessment_choices" (
    "choice_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "choice_text" character varying(300) NOT NULL,
    "is_correct" boolean DEFAULT false NOT NULL,
    "choice_order" smallint DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."assessment_choices" OWNER TO "postgres";


ALTER TABLE "public"."assessment_choices" ALTER COLUMN "choice_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessment_choices_choice_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessment_questions" (
    "question_id" bigint NOT NULL,
    "test_id" bigint NOT NULL,
    "question_text" "text" NOT NULL,
    "question_order" smallint DEFAULT 1 NOT NULL,
    "points" smallint DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."assessment_questions" OWNER TO "postgres";


ALTER TABLE "public"."assessment_questions" ALTER COLUMN "question_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessment_questions_question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessment_tests" (
    "test_id" bigint NOT NULL,
    "admin_id" bigint NOT NULL,
    "trade_category" "text" NOT NULL,
    "test_title" character varying(150) NOT NULL,
    "passing_score" numeric(5,2) DEFAULT 75.00 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone,
    CONSTRAINT "assessment_tests_trade_category_check" CHECK (("trade_category" = ANY (ARRAY['Carpenter'::"text", 'Electrician'::"text", 'Kasambahay'::"text"])))
);


ALTER TABLE "public"."assessment_tests" OWNER TO "postgres";


ALTER TABLE "public"."assessment_tests" ALTER COLUMN "test_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessment_tests_test_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assessments" (
    "assessment_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "admin_id" bigint NOT NULL,
    "test_score" numeric(5,2),
    "lgu_status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "remarks" "text",
    "assessed_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "assessments_lgu_status_check" CHECK (("lgu_status" = ANY (ARRAY['Pending'::"text", 'Passed'::"text", 'Failed'::"text"])))
);


ALTER TABLE "public"."assessments" OWNER TO "postgres";


ALTER TABLE "public"."assessments" ALTER COLUMN "assessment_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assessments_assessment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customer_otps" (
    "email" character varying(150) NOT NULL,
    "otp" character varying(6) NOT NULL,
    "expires_at" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."customer_otps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."customers" (
    "customer_id" bigint NOT NULL,
    "user_id" bigint,
    "preferred_barangay" character varying(100)
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


ALTER TABLE "public"."customers" ALTER COLUMN "customer_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."customers_customer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."employment_details" (
    "employment_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "employment_status" "text" NOT NULL,
    "employment_type" "text" DEFAULT 'Not Applicable'::"text" NOT NULL,
    "unemployment_reason" "text" DEFAULT 'Not Applicable'::"text" NOT NULL,
    "self_employed_spec" character varying(100),
    "highest_education" "text",
    "school_last_attended" character varying(150),
    "course_completed" character varying(150),
    "year_graduated" character varying(4),
    "employment_history" "text",
    CONSTRAINT "employment_details_employment_status_check" CHECK (("employment_status" = ANY (ARRAY['Employed'::"text", 'Unemployed'::"text"]))),
    CONSTRAINT "employment_details_employment_type_check" CHECK (("employment_type" = ANY (ARRAY['Wage Employed'::"text", 'Self Employed'::"text", 'Not Applicable'::"text"])))
);


ALTER TABLE "public"."employment_details" OWNER TO "postgres";


ALTER TABLE "public"."employment_details" ALTER COLUMN "employment_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."employment_details_employment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_requests" (
    "job_id" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "service_description" "text" NOT NULL,
    "service_street" character varying(150),
    "service_barangay" character varying(100) NOT NULL,
    "job_status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "requested_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "accepted_at" timestamp with time zone,
    "started_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    CONSTRAINT "job_requests_job_status_check" CHECK (("job_status" = ANY (ARRAY['Pending'::"text", 'Accepted'::"text", 'Declined'::"text", 'Ongoing'::"text", 'Completed'::"text", 'Cancelled'::"text"])))
);


ALTER TABLE "public"."job_requests" OWNER TO "postgres";


ALTER TABLE "public"."job_requests" ALTER COLUMN "job_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_requests_job_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."nsrp_details" (
    "nsrp_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "last_name" character varying(80) NOT NULL,
    "first_name" character varying(80) NOT NULL,
    "middle_name" character varying(80),
    "suffix" character varying(10),
    "date_of_birth" "date" NOT NULL,
    "age" smallint NOT NULL,
    "sex" "text" NOT NULL,
    "civil_status" "text" NOT NULL,
    "pres_street" character varying(150),
    "pres_barangay" character varying(100) NOT NULL,
    "pres_city" character varying(100) NOT NULL,
    "pres_province" character varying(100) NOT NULL,
    "perm_street" character varying(150),
    "perm_barangay" character varying(100),
    "perm_city" character varying(100),
    "perm_province" character varying(100),
    "father_name" character varying(150),
    "father_contact" character varying(15),
    "mother_name" character varying(150),
    "mother_contact" character varying(15),
    "parents_civil_status" "text",
    "is_4ps_beneficiary" boolean DEFAULT false NOT NULL,
    "is_indigent" boolean DEFAULT false NOT NULL,
    "is_pwd" boolean DEFAULT false NOT NULL,
    "is_senior_citizen" boolean DEFAULT false NOT NULL,
    "is_solo_parent" boolean DEFAULT false NOT NULL,
    CONSTRAINT "nsrp_details_civil_status_check" CHECK (("civil_status" = ANY (ARRAY['Single'::"text", 'Married'::"text", 'Widowed'::"text", 'Separated'::"text"]))),
    CONSTRAINT "nsrp_details_parents_civil_status_check" CHECK (("parents_civil_status" = ANY (ARRAY['Living Together'::"text", 'Solo Parent'::"text", 'Separated'::"text"]))),
    CONSTRAINT "nsrp_details_sex_check" CHECK (("sex" = ANY (ARRAY['Male'::"text", 'Female'::"text"])))
);


ALTER TABLE "public"."nsrp_details" OWNER TO "postgres";


ALTER TABLE "public"."nsrp_details" ALTER COLUMN "nsrp_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."nsrp_details_nsrp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."provider_files" (
    "file_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "file_type" "text" NOT NULL,
    "file_path" character varying(300) NOT NULL,
    "original_name" character varying(255) NOT NULL,
    "uploaded_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "provider_files_file_type_check" CHECK (("file_type" = ANY (ARRAY['national_id'::"text", 'national_id_back'::"text", 'photo'::"text", 'secondary_id'::"text", 'certificate'::"text"])))
);


ALTER TABLE "public"."provider_files" OWNER TO "postgres";


ALTER TABLE "public"."provider_files" ALTER COLUMN "file_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."provider_files_file_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."providers" (
    "provider_id" bigint NOT NULL,
    "user_id" bigint,
    "trade_category" "text" NOT NULL,
    "admin_status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "rejected_at" timestamp with time zone,
    "average_rating" numeric(3,2) DEFAULT 0.00 NOT NULL,
    "bio" "text",
    CONSTRAINT "providers_admin_status_check" CHECK (("admin_status" = ANY (ARRAY['Pending'::"text", 'Approved'::"text", 'Rejected'::"text", 'Suspended'::"text"]))),
    CONSTRAINT "providers_trade_category_check" CHECK (("trade_category" = ANY (ARRAY['Carpenter'::"text", 'Electrician'::"text", 'Kasambahay'::"text", 'Nanny'::"text", 'Other'::"text"])))
);


ALTER TABLE "public"."providers" OWNER TO "postgres";


ALTER TABLE "public"."providers" ALTER COLUMN "provider_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."providers_provider_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ratings" (
    "rating_id" bigint NOT NULL,
    "job_id" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "stars" smallint NOT NULL,
    "review_text" "text",
    "rated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "ratings_stars_check" CHECK ((("stars" >= 1) AND ("stars" <= 5)))
);


ALTER TABLE "public"."ratings" OWNER TO "postgres";


ALTER TABLE "public"."ratings" ALTER COLUMN "rating_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ratings_rating_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."skills" (
    "skill_id" bigint NOT NULL,
    "provider_id" bigint NOT NULL,
    "skill_name" character varying(100) NOT NULL,
    "description" character varying(255),
    "years_experience" smallint DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."skills" OWNER TO "postgres";


ALTER TABLE "public"."skills" ALTER COLUMN "skill_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."skills_skill_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" bigint NOT NULL,
    "auth_id" "uuid",
    "full_name" character varying(150) NOT NULL,
    "email" character varying(150) NOT NULL,
    "password_hash" character varying(255) NOT NULL,
    "role" "text" NOT NULL,
    "contact_number" character varying(15),
    "barangay" character varying(100) NOT NULL,
    "municipality" character varying(100) DEFAULT 'Anini-y'::character varying NOT NULL,
    "province" character varying(100) DEFAULT 'Antique'::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone,
    "onboarding_complete" boolean DEFAULT false NOT NULL,
    CONSTRAINT "users_role_check" CHECK (("role" = ANY (ARRAY['Customer'::"text", 'Provider'::"text", 'Admin'::"text"])))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("admin_id");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."assessment_answers"
    ADD CONSTRAINT "assessment_answers_attempt_id_question_id_key" UNIQUE ("attempt_id", "question_id");



ALTER TABLE ONLY "public"."assessment_answers"
    ADD CONSTRAINT "assessment_answers_pkey" PRIMARY KEY ("answer_id");



ALTER TABLE ONLY "public"."assessment_attempts"
    ADD CONSTRAINT "assessment_attempts_pkey" PRIMARY KEY ("attempt_id");



ALTER TABLE ONLY "public"."assessment_choices"
    ADD CONSTRAINT "assessment_choices_pkey" PRIMARY KEY ("choice_id");



ALTER TABLE ONLY "public"."assessment_questions"
    ADD CONSTRAINT "assessment_questions_pkey" PRIMARY KEY ("question_id");



ALTER TABLE ONLY "public"."assessment_tests"
    ADD CONSTRAINT "assessment_tests_pkey" PRIMARY KEY ("test_id");



ALTER TABLE ONLY "public"."assessment_tests"
    ADD CONSTRAINT "assessment_tests_trade_category_is_active_key" UNIQUE ("trade_category", "is_active");



ALTER TABLE ONLY "public"."assessments"
    ADD CONSTRAINT "assessments_pkey" PRIMARY KEY ("assessment_id");



ALTER TABLE ONLY "public"."customer_otps"
    ADD CONSTRAINT "customer_otps_pkey" PRIMARY KEY ("email");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("customer_id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."employment_details"
    ADD CONSTRAINT "employment_details_pkey" PRIMARY KEY ("employment_id");



ALTER TABLE ONLY "public"."employment_details"
    ADD CONSTRAINT "employment_details_provider_id_key" UNIQUE ("provider_id");



ALTER TABLE ONLY "public"."job_requests"
    ADD CONSTRAINT "job_requests_pkey" PRIMARY KEY ("job_id");



ALTER TABLE ONLY "public"."nsrp_details"
    ADD CONSTRAINT "nsrp_details_pkey" PRIMARY KEY ("nsrp_id");



ALTER TABLE ONLY "public"."nsrp_details"
    ADD CONSTRAINT "nsrp_details_provider_id_key" UNIQUE ("provider_id");



ALTER TABLE ONLY "public"."provider_files"
    ADD CONSTRAINT "provider_files_pkey" PRIMARY KEY ("file_id");



ALTER TABLE ONLY "public"."providers"
    ADD CONSTRAINT "providers_pkey" PRIMARY KEY ("provider_id");



ALTER TABLE ONLY "public"."providers"
    ADD CONSTRAINT "providers_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_job_id_key" UNIQUE ("job_id");



ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_pkey" PRIMARY KEY ("rating_id");



ALTER TABLE ONLY "public"."skills"
    ADD CONSTRAINT "skills_pkey" PRIMARY KEY ("skill_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");



CREATE OR REPLACE TRIGGER "trg_update_avg_rating" AFTER INSERT OR UPDATE ON "public"."ratings" FOR EACH ROW EXECUTE FUNCTION "public"."update_avg_rating"();



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_answers"
    ADD CONSTRAINT "assessment_answers_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "public"."assessment_attempts"("attempt_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_answers"
    ADD CONSTRAINT "assessment_answers_chosen_choice_id_fkey" FOREIGN KEY ("chosen_choice_id") REFERENCES "public"."assessment_choices"("choice_id");



ALTER TABLE ONLY "public"."assessment_answers"
    ADD CONSTRAINT "assessment_answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."assessment_questions"("question_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_attempts"
    ADD CONSTRAINT "assessment_attempts_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_attempts"
    ADD CONSTRAINT "assessment_attempts_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "public"."assessment_tests"("test_id");



ALTER TABLE ONLY "public"."assessment_choices"
    ADD CONSTRAINT "assessment_choices_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."assessment_questions"("question_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_questions"
    ADD CONSTRAINT "assessment_questions_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "public"."assessment_tests"("test_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assessment_tests"
    ADD CONSTRAINT "assessment_tests_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "public"."admins"("admin_id");



ALTER TABLE ONLY "public"."assessments"
    ADD CONSTRAINT "assessments_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "public"."admins"("admin_id");



ALTER TABLE ONLY "public"."assessments"
    ADD CONSTRAINT "assessments_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."employment_details"
    ADD CONSTRAINT "employment_details_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_requests"
    ADD CONSTRAINT "job_requests_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_requests"
    ADD CONSTRAINT "job_requests_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."nsrp_details"
    ADD CONSTRAINT "nsrp_details_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."provider_files"
    ADD CONSTRAINT "provider_files_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."providers"
    ADD CONSTRAINT "providers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."job_requests"("job_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skills"
    ADD CONSTRAINT "skills_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admins update providers" ON "public"."providers" FOR UPDATE USING ("public"."is_admin"());



CREATE POLICY "Admins view NSRP" ON "public"."nsrp_details" FOR SELECT USING ("public"."is_admin"());



CREATE POLICY "Admins view all providers" ON "public"."providers" FOR SELECT USING ("public"."is_admin"());



CREATE POLICY "Enable read access for all users" ON "public"."assessment_attempts" FOR SELECT USING (true);



CREATE POLICY "Public sees approved providers" ON "public"."providers" FOR SELECT USING (("admin_status" = 'Approved'::"text"));



CREATE POLICY "Users insert own profile" ON "public"."users" FOR INSERT WITH CHECK (("auth_id" = "auth"."uid"()));



CREATE POLICY "Users update own profile" ON "public"."users" FOR UPDATE USING (("auth_id" = "auth"."uid"()));



CREATE POLICY "Users view own profile" ON "public"."users" FOR SELECT USING ((("auth_id" = "auth"."uid"()) OR "public"."is_admin"()));



ALTER TABLE "public"."admins" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessment_answers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessment_attempts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessment_choices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessment_questions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessment_tests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assessments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customer_otps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."employment_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."nsrp_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."provider_files" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."providers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ratings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."skills" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_avg_rating"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_avg_rating"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_avg_rating"() TO "service_role";


















GRANT ALL ON TABLE "public"."admins" TO "anon";
GRANT ALL ON TABLE "public"."admins" TO "authenticated";
GRANT ALL ON TABLE "public"."admins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessment_answers" TO "anon";
GRANT ALL ON TABLE "public"."assessment_answers" TO "authenticated";
GRANT ALL ON TABLE "public"."assessment_answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessment_answers_answer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessment_answers_answer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessment_answers_answer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessment_attempts" TO "anon";
GRANT ALL ON TABLE "public"."assessment_attempts" TO "authenticated";
GRANT ALL ON TABLE "public"."assessment_attempts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessment_attempts_attempt_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessment_attempts_attempt_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessment_attempts_attempt_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessment_choices" TO "anon";
GRANT ALL ON TABLE "public"."assessment_choices" TO "authenticated";
GRANT ALL ON TABLE "public"."assessment_choices" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessment_choices_choice_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessment_choices_choice_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessment_choices_choice_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessment_questions" TO "anon";
GRANT ALL ON TABLE "public"."assessment_questions" TO "authenticated";
GRANT ALL ON TABLE "public"."assessment_questions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessment_questions_question_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessment_questions_question_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessment_questions_question_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessment_tests" TO "anon";
GRANT ALL ON TABLE "public"."assessment_tests" TO "authenticated";
GRANT ALL ON TABLE "public"."assessment_tests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessment_tests_test_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessment_tests_test_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessment_tests_test_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assessments" TO "anon";
GRANT ALL ON TABLE "public"."assessments" TO "authenticated";
GRANT ALL ON TABLE "public"."assessments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assessments_assessment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assessments_assessment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assessments_assessment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customer_otps" TO "anon";
GRANT ALL ON TABLE "public"."customer_otps" TO "authenticated";
GRANT ALL ON TABLE "public"."customer_otps" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customers_customer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customers_customer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customers_customer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."employment_details" TO "anon";
GRANT ALL ON TABLE "public"."employment_details" TO "authenticated";
GRANT ALL ON TABLE "public"."employment_details" TO "service_role";



GRANT ALL ON SEQUENCE "public"."employment_details_employment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."employment_details_employment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."employment_details_employment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_requests" TO "anon";
GRANT ALL ON TABLE "public"."job_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."job_requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_requests_job_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_requests_job_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_requests_job_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."nsrp_details" TO "anon";
GRANT ALL ON TABLE "public"."nsrp_details" TO "authenticated";
GRANT ALL ON TABLE "public"."nsrp_details" TO "service_role";



GRANT ALL ON SEQUENCE "public"."nsrp_details_nsrp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nsrp_details_nsrp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nsrp_details_nsrp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."provider_files" TO "anon";
GRANT ALL ON TABLE "public"."provider_files" TO "authenticated";
GRANT ALL ON TABLE "public"."provider_files" TO "service_role";



GRANT ALL ON SEQUENCE "public"."provider_files_file_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."provider_files_file_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."provider_files_file_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."providers" TO "anon";
GRANT ALL ON TABLE "public"."providers" TO "authenticated";
GRANT ALL ON TABLE "public"."providers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."providers_provider_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."providers_provider_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."providers_provider_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ratings" TO "anon";
GRANT ALL ON TABLE "public"."ratings" TO "authenticated";
GRANT ALL ON TABLE "public"."ratings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ratings_rating_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ratings_rating_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ratings_rating_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."skills" TO "anon";
GRANT ALL ON TABLE "public"."skills" TO "authenticated";
GRANT ALL ON TABLE "public"."skills" TO "service_role";



GRANT ALL ON SEQUENCE "public"."skills_skill_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."skills_skill_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."skills_skill_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































