-- ═══════════════════════════════════════════════════════════════════════
--  CommuniServe — pre-set services, fixed pricing & custom negotiation
--
--  1. service_catalog    trade-specific pre-set services (seeded below)
--  2. provider_services  a provider's activated pre-sets + their fixed price
--  3. job_requests       + request_type, provider_service_id, service_name,
--                          agreed_price, payment_structure (all nullable —
--                          NULL request_type = legacy free-text request)
--  4. job_offers         bidding history for "Custom Service" requests
--  5. guard trigger      pricing fields can only be written by the
--                          SECURITY DEFINER functions below
--  6. functions          create_service_request, respond_to_job_offer,
--                          get_customer_jobs, get_provider_jobs
--
--  NEGOTIATION STATE MACHINE (no change to the job_status CHECK):
--    custom request created  → job_status 'Pending', customer's offer #1
--    whoever did NOT make the latest offer may:
--      accept   → 'Accepted', agreed_price = latest offer
--      decline  → 'Declined' (provider) / 'Cancelled' (customer)
--      counter  → new offer row, turn passes to the other party
--  Fixed requests keep the existing flow: 'Pending' → provider Accept /
--  Decline, with agreed_price snapshotted from the provider's price.
--
--  ADDITIVE ONLY — no existing column, constraint, policy or row is
--  dropped or rewritten. Idempotent — safe to re-run in the SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════
--  1. SERVICE CATALOG (pre-sets per trade)
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "public"."service_catalog" (
    "catalog_id"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trade_category"  text        NOT NULL,
    "service_name"    varchar(80) NOT NULL,
    "description"     text,
    "price_unit"      varchar(30) NOT NULL DEFAULT 'per job',
    "sort_order"      smallint    NOT NULL DEFAULT 1,
    "is_active"       boolean     NOT NULL DEFAULT true,
    "created_at"      timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'service_catalog_trade_check') THEN
        ALTER TABLE "public"."service_catalog" ADD CONSTRAINT "service_catalog_trade_check"
            CHECK ("trade_category" IN ('Carpenter', 'Electrician', 'Kasambahay'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'service_catalog_trade_name_key') THEN
        ALTER TABLE "public"."service_catalog" ADD CONSTRAINT "service_catalog_trade_name_key"
            UNIQUE ("trade_category", "service_name");
    END IF;
END $$;

INSERT INTO "public"."service_catalog" ("trade_category", "service_name", "description", "price_unit", "sort_order") VALUES
    ('Kasambahay',  'Full Day',  'Whole-day household help, 8 AM – 5 PM.',                    'per day',      1),
    ('Kasambahay',  'Half Day',  'Half-day household help (about 4 hours).',                  'per half day', 2),
    ('Kasambahay',  'Laundry',   'Washing, drying and folding of clothes.',                   'per job',      3),
    ('Kasambahay',  '1 Floor',   'Cleaning of one floor of the house.',                       'per cleaning', 4),
    ('Kasambahay',  '2 Floors',  'Cleaning of two floors of the house.',                      'per cleaning', 5),
    ('Kasambahay',  'Full House','Cleaning of the entire house.',                             'per cleaning', 6),

    ('Electrician', 'Power & Outlet Issues',           'Fixing dead outlets, adding new outlets, replacing switches.', 'per job', 1),
    ('Electrician', 'Lighting Repairs & Enhancements', 'Flickering lights, new fixtures, emergency lights.',           'per job', 2),
    ('Electrician', 'Indoor Circuit & Panel Work',     'Breaker, circuit and panel board work inside the home.',       'per job', 3),
    ('Electrician', 'Appliance Fix',                   'Diagnosis and repair of household appliances.',                'per job', 4),

    ('Carpenter',   'Carpentry & Woodwork', 'Furniture, cabinets, doors, frames and wood repairs.',      'per job', 1),
    ('Carpenter',   'Concrete & Masonry',   'Hollow blocks, plastering, flooring and concrete repairs.', 'per job', 2),
    ('Carpenter',   'Roofing & Ceilings',   'Roof leaks, GI sheet replacement and ceiling repairs.',     'per job', 3),
    ('Carpenter',   'Minor Plumbing',       'Leaking pipes, faucets and drainage fixes.',                'per job', 4)
ON CONFLICT ("trade_category", "service_name") DO NOTHING;


-- ═══════════════════════════════════════════════════════════════════════
--  2. PROVIDER SERVICES (activated pre-sets + fixed price)
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "public"."provider_services" (
    "provider_service_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "provider_id"         bigint        NOT NULL REFERENCES "public"."providers"("provider_id") ON DELETE CASCADE,
    "catalog_id"          bigint        NOT NULL REFERENCES "public"."service_catalog"("catalog_id"),
    "price"               numeric(10,2) NOT NULL,
    "is_active"           boolean       NOT NULL DEFAULT true,
    "created_at"          timestamptz   NOT NULL DEFAULT now(),
    "updated_at"          timestamptz
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'provider_services_price_check') THEN
        ALTER TABLE "public"."provider_services" ADD CONSTRAINT "provider_services_price_check"
            CHECK ("price" > 0 AND "price" <= 1000000);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'provider_services_provider_catalog_key') THEN
        ALTER TABLE "public"."provider_services" ADD CONSTRAINT "provider_services_provider_catalog_key"
            UNIQUE ("provider_id", "catalog_id");
    END IF;
END $$;


-- ═══════════════════════════════════════════════════════════════════════
--  3. JOB_REQUESTS — pricing columns (nullable; legacy rows stay valid)
-- ═══════════════════════════════════════════════════════════════════════

ALTER TABLE "public"."job_requests" ADD COLUMN IF NOT EXISTS "request_type"        text;
ALTER TABLE "public"."job_requests" ADD COLUMN IF NOT EXISTS "provider_service_id" bigint REFERENCES "public"."provider_services"("provider_service_id");
ALTER TABLE "public"."job_requests" ADD COLUMN IF NOT EXISTS "service_name"        varchar(80);
ALTER TABLE "public"."job_requests" ADD COLUMN IF NOT EXISTS "agreed_price"        numeric(10,2);
ALTER TABLE "public"."job_requests" ADD COLUMN IF NOT EXISTS "payment_structure"   text;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_requests_request_type_check') THEN
        ALTER TABLE "public"."job_requests" ADD CONSTRAINT "job_requests_request_type_check"
            CHECK ("request_type" IS NULL OR "request_type" IN ('fixed', 'custom'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_requests_agreed_price_check') THEN
        ALTER TABLE "public"."job_requests" ADD CONSTRAINT "job_requests_agreed_price_check"
            CHECK ("agreed_price" IS NULL OR "agreed_price" > 0);
    END IF;
    -- Panday custom bids: Arawan (daily rate) or Pakyawan (per-project contract)
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_requests_payment_structure_check') THEN
        ALTER TABLE "public"."job_requests" ADD CONSTRAINT "job_requests_payment_structure_check"
            CHECK ("payment_structure" IS NULL OR "payment_structure" IN ('arawan', 'pakyawan'));
    END IF;
END $$;


-- ═══════════════════════════════════════════════════════════════════════
--  4. JOB_OFFERS — negotiation history for custom requests
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "public"."job_offers" (
    "offer_id"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id"      bigint        NOT NULL REFERENCES "public"."job_requests"("job_id") ON DELETE CASCADE,
    "offered_by"  text          NOT NULL,
    "amount"      numeric(10,2) NOT NULL,
    "note"        text,
    "created_at"  timestamptz   NOT NULL DEFAULT now()
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_offers_offered_by_check') THEN
        ALTER TABLE "public"."job_offers" ADD CONSTRAINT "job_offers_offered_by_check"
            CHECK ("offered_by" IN ('customer', 'provider'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_offers_amount_check') THEN
        ALTER TABLE "public"."job_offers" ADD CONSTRAINT "job_offers_amount_check"
            CHECK ("amount" > 0 AND "amount" <= 1000000);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "job_offers_job_id_idx" ON "public"."job_offers" ("job_id", "created_at");


-- ═══════════════════════════════════════════════════════════════════════
--  5. ROW LEVEL SECURITY (BR-11)
-- ═══════════════════════════════════════════════════════════════════════

ALTER TABLE "public"."service_catalog"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."provider_services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."job_offers"        ENABLE ROW LEVEL SECURITY;

-- Catalog is public reference data.
DROP POLICY IF EXISTS "Anyone reads the service catalog" ON "public"."service_catalog";
CREATE POLICY "Anyone reads the service catalog"
    ON "public"."service_catalog" FOR SELECT
    USING (true);

-- Customers see the active services of approved providers.
DROP POLICY IF EXISTS "Public sees active services of approved providers" ON "public"."provider_services";
CREATE POLICY "Public sees active services of approved providers"
    ON "public"."provider_services" FOR SELECT
    USING (
        "is_active"
        AND EXISTS (
            SELECT 1 FROM "public"."providers" p
            WHERE p."provider_id" = "provider_services"."provider_id"
              AND p."admin_status" = 'Approved'
        )
    );

-- Providers manage their own rows, and only for services of their own trade.
DROP POLICY IF EXISTS "Providers manage own services" ON "public"."provider_services";
CREATE POLICY "Providers manage own services"
    ON "public"."provider_services" FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM "public"."providers" p
            JOIN "public"."users" u ON u."user_id" = p."user_id"
            WHERE p."provider_id" = "provider_services"."provider_id"
              AND u."auth_id" = "auth"."uid"()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "public"."providers" p
            JOIN "public"."users" u           ON u."user_id"    = p."user_id"
            JOIN "public"."service_catalog" c ON c."catalog_id" = "provider_services"."catalog_id"
            WHERE p."provider_id"    = "provider_services"."provider_id"
              AND u."auth_id"        = "auth"."uid"()
              AND c."trade_category" = p."trade_category"
        )
    );

DROP POLICY IF EXISTS "Admins view provider services" ON "public"."provider_services";
CREATE POLICY "Admins view provider services"
    ON "public"."provider_services" FOR SELECT
    USING ("public"."is_admin"());

-- Offers are visible to the two parties of the job. There is no INSERT
-- policy: offers are written only by respond_to_job_offer() /
-- create_service_request(), which enforce whose turn it is.
DROP POLICY IF EXISTS "Parties view job offers" ON "public"."job_offers";
CREATE POLICY "Parties view job offers"
    ON "public"."job_offers" FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM "public"."job_requests" j
            LEFT JOIN "public"."customers" c ON c."customer_id" = j."customer_id"
            LEFT JOIN "public"."users" cu    ON cu."user_id"    = c."user_id"
            LEFT JOIN "public"."providers" p ON p."provider_id" = j."provider_id"
            LEFT JOIN "public"."users" pu    ON pu."user_id"    = p."user_id"
            WHERE j."job_id" = "job_offers"."job_id"
              AND "auth"."uid"() IN (cu."auth_id", pu."auth_id")
        )
    );

DROP POLICY IF EXISTS "Admins view job offers" ON "public"."job_offers";
CREATE POLICY "Admins view job offers"
    ON "public"."job_offers" FOR SELECT
    USING ("public"."is_admin"());


-- ═══════════════════════════════════════════════════════════════════════
--  6. GUARD — pricing can't be forged through the plain table policies
--
--  The existing "Customers create own requests" INSERT policy and
--  "Providers update own requests" UPDATE policy would otherwise let a
--  client write any agreed_price. This trigger rejects pricing writes and
--  custom-request status changes unless they come from the SECURITY
--  DEFINER functions below, which set a transaction-local flag.
--  Legacy inserts (no pricing columns) and the provider's
--  Accept/Decline/Start/Complete on fixed requests are unaffected.
-- ═══════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION "public"."guard_job_pricing"()
RETURNS trigger
LANGUAGE plpgsql
SET "search_path" = "public"
AS $$
BEGIN
    IF current_setting('communiserve.trusted_write', true) = 'on' THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.request_type IS NOT NULL OR NEW.agreed_price IS NOT NULL
           OR NEW.provider_service_id IS NOT NULL OR NEW.payment_structure IS NOT NULL
           OR NEW.service_name IS NOT NULL THEN
            RAISE EXCEPTION 'Priced requests must be created through create_service_request()';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.request_type        IS DISTINCT FROM OLD.request_type
       OR NEW.agreed_price     IS DISTINCT FROM OLD.agreed_price
       OR NEW.provider_service_id IS DISTINCT FROM OLD.provider_service_id
       OR NEW.payment_structure IS DISTINCT FROM OLD.payment_structure
       OR NEW.service_name     IS DISTINCT FROM OLD.service_name THEN
        RAISE EXCEPTION 'Pricing fields can only change through the negotiation functions';
    END IF;

    IF OLD.request_type = 'custom' AND OLD.job_status = 'Pending'
       AND NEW.job_status IS DISTINCT FROM OLD.job_status THEN
        RAISE EXCEPTION 'Custom requests are settled through respond_to_job_offer()';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "guard_job_pricing" ON "public"."job_requests";
CREATE TRIGGER "guard_job_pricing"
    BEFORE INSERT OR UPDATE ON "public"."job_requests"
    FOR EACH ROW EXECUTE FUNCTION "public"."guard_job_pricing"();


-- ═══════════════════════════════════════════════════════════════════════
--  7. WRITE FUNCTIONS
-- ═══════════════════════════════════════════════════════════════════════

-- ── 7a. Customer books a fixed service or opens a custom negotiation ───
CREATE OR REPLACE FUNCTION "public"."create_service_request"(
    "p_provider_id"         bigint,
    "p_request_type"        text,
    "p_provider_service_id" bigint  DEFAULT NULL,
    "p_description"         text    DEFAULT NULL,
    "p_street"              text    DEFAULT NULL,
    "p_barangay"            text    DEFAULT NULL,
    "p_proposed_price"      numeric DEFAULT NULL,
    "p_payment_structure"   text    DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET "search_path" = "public"
AS $$
DECLARE
    v_customer_id  bigint;
    v_trade        text;
    v_price        numeric(10,2);
    v_service_name text;
    v_description  text := NULLIF(btrim(p_description), '');
    v_job_id       bigint;
BEGIN
    SELECT c.customer_id INTO v_customer_id
    FROM customers c JOIN users u ON u.user_id = c.user_id
    WHERE u.auth_id = auth.uid();
    IF v_customer_id IS NULL THEN
        RAISE EXCEPTION 'Only resident accounts can send requests.';
    END IF;

    SELECT trade_category INTO v_trade
    FROM providers WHERE provider_id = p_provider_id AND admin_status = 'Approved';
    IF v_trade IS NULL THEN
        RAISE EXCEPTION 'This provider is not available.';
    END IF;

    IF NULLIF(btrim(p_barangay), '') IS NULL THEN
        RAISE EXCEPTION 'Please choose the barangay.';
    END IF;

    PERFORM set_config('communiserve.trusted_write', 'on', true);

    IF p_request_type = 'fixed' THEN
        SELECT ps.price, sc.service_name INTO v_price, v_service_name
        FROM provider_services ps
        JOIN service_catalog sc ON sc.catalog_id = ps.catalog_id
        WHERE ps.provider_service_id = p_provider_service_id
          AND ps.provider_id = p_provider_id
          AND ps.is_active;
        IF v_price IS NULL THEN
            RAISE EXCEPTION 'That service is no longer offered.';
        END IF;

        INSERT INTO job_requests (
            customer_id, provider_id, service_description, service_street, service_barangay,
            job_status, request_type, provider_service_id, service_name, agreed_price
        ) VALUES (
            v_customer_id, p_provider_id, COALESCE(v_description, v_service_name),
            NULLIF(btrim(p_street), ''), btrim(p_barangay),
            'Pending', 'fixed', p_provider_service_id, v_service_name, v_price
        )
        RETURNING job_id INTO v_job_id;

    ELSIF p_request_type = 'custom' THEN
        IF v_description IS NULL THEN
            RAISE EXCEPTION 'Please describe the work you need.';
        END IF;
        IF p_proposed_price IS NULL OR p_proposed_price <= 0 OR p_proposed_price > 1000000 THEN
            RAISE EXCEPTION 'Please enter a valid proposed price.';
        END IF;
        -- COALESCE: a NULL structure must fail this check, not slip past NOT IN.
        IF v_trade = 'Carpenter' AND COALESCE(p_payment_structure, '') NOT IN ('arawan', 'pakyawan') THEN
            RAISE EXCEPTION 'Choose Arawan (daily rate) or Pakyawan (per project).';
        END IF;
        IF v_trade <> 'Carpenter' AND p_payment_structure IS NOT NULL THEN
            RAISE EXCEPTION 'Payment structure only applies to Panday requests.';
        END IF;

        INSERT INTO job_requests (
            customer_id, provider_id, service_description, service_street, service_barangay,
            job_status, request_type, service_name, payment_structure
        ) VALUES (
            v_customer_id, p_provider_id, v_description,
            NULLIF(btrim(p_street), ''), btrim(p_barangay),
            'Pending', 'custom', 'Custom Service', p_payment_structure
        )
        RETURNING job_id INTO v_job_id;

        INSERT INTO job_offers (job_id, offered_by, amount)
        VALUES (v_job_id, 'customer', round(p_proposed_price, 2));

    ELSE
        RAISE EXCEPTION 'Unknown request type.';
    END IF;

    RETURN v_job_id;
END;
$$;

ALTER FUNCTION "public"."create_service_request"(bigint, text, bigint, text, text, text, numeric, text) OWNER TO "postgres";
REVOKE EXECUTE ON FUNCTION "public"."create_service_request"(bigint, text, bigint, text, text, text, numeric, text) FROM PUBLIC, "anon";
GRANT  EXECUTE ON FUNCTION "public"."create_service_request"(bigint, text, bigint, text, text, text, numeric, text) TO "authenticated";

-- ── 7b. Either party answers the latest offer on a custom request ──────
CREATE OR REPLACE FUNCTION "public"."respond_to_job_offer"(
    "p_job_id" bigint,
    "p_action" text,
    "p_amount" numeric DEFAULT NULL,
    "p_note"   text    DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET "search_path" = "public"
AS $$
DECLARE
    v_job    job_requests%ROWTYPE;
    v_last   job_offers%ROWTYPE;
    v_actor  text;
    v_status text;
BEGIN
    -- Row lock: two quick taps (or both parties at once) can't both win.
    SELECT * INTO v_job FROM job_requests WHERE job_id = p_job_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Request not found.';
    END IF;

    IF EXISTS (SELECT 1 FROM customers c JOIN users u ON u.user_id = c.user_id
               WHERE c.customer_id = v_job.customer_id AND u.auth_id = auth.uid()) THEN
        v_actor := 'customer';
    ELSIF EXISTS (SELECT 1 FROM providers p JOIN users u ON u.user_id = p.user_id
                  WHERE p.provider_id = v_job.provider_id AND u.auth_id = auth.uid()) THEN
        v_actor := 'provider';
    ELSE
        RAISE EXCEPTION 'This is not your request.';
    END IF;

    IF v_job.request_type IS DISTINCT FROM 'custom' THEN
        RAISE EXCEPTION 'Only custom requests can be negotiated.';
    END IF;
    IF v_job.job_status <> 'Pending' THEN
        RAISE EXCEPTION 'This negotiation is already closed.';
    END IF;

    SELECT * INTO v_last FROM job_offers
    WHERE job_id = p_job_id
    ORDER BY created_at DESC, offer_id DESC
    LIMIT 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'There is no offer to respond to.';
    END IF;
    IF v_last.offered_by = v_actor THEN
        RAISE EXCEPTION 'Waiting for the other party to respond to your offer.';
    END IF;

    PERFORM set_config('communiserve.trusted_write', 'on', true);

    IF p_action = 'accept' THEN
        UPDATE job_requests
        SET job_status = 'Accepted', agreed_price = v_last.amount, accepted_at = now()
        WHERE job_id = p_job_id;
        RETURN 'Accepted';

    ELSIF p_action = 'decline' THEN
        v_status := CASE WHEN v_actor = 'provider' THEN 'Declined' ELSE 'Cancelled' END;
        UPDATE job_requests SET job_status = v_status WHERE job_id = p_job_id;
        RETURN v_status;

    ELSIF p_action = 'counter' THEN
        IF p_amount IS NULL OR p_amount <= 0 OR p_amount > 1000000 THEN
            RAISE EXCEPTION 'Please enter a valid amount.';
        END IF;
        INSERT INTO job_offers (job_id, offered_by, amount, note)
        VALUES (p_job_id, v_actor, round(p_amount, 2), NULLIF(btrim(p_note), ''));
        RETURN 'Pending';

    ELSE
        RAISE EXCEPTION 'Unknown action.';
    END IF;
END;
$$;

ALTER FUNCTION "public"."respond_to_job_offer"(bigint, text, numeric, text) OWNER TO "postgres";
REVOKE EXECUTE ON FUNCTION "public"."respond_to_job_offer"(bigint, text, numeric, text) FROM PUBLIC, "anon";
GRANT  EXECUTE ON FUNCTION "public"."respond_to_job_offer"(bigint, text, numeric, text) TO "authenticated";


-- ═══════════════════════════════════════════════════════════════════════
--  8. READ FUNCTIONS — each side's jobs with pricing + offer history
--  (new functions; get_my_customer_requests / get_my_provider_requests
--   are left untouched)
-- ═══════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION "public"."get_customer_jobs"()
RETURNS TABLE (
    "job_id"              bigint,
    "provider_id"         bigint,
    "provider_name"       text,
    "trade_category"      text,
    "request_type"        text,
    "service_name"        text,
    "service_description" text,
    "service_street"      text,
    "service_barangay"    text,
    "job_status"          text,
    "agreed_price"        numeric,
    "payment_structure"   text,
    "requested_at"        timestamptz,
    "offers"              jsonb
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET "search_path" = "public"
AS $$
    SELECT
        j.job_id,
        j.provider_id,
        pu.full_name::text,
        p.trade_category::text,
        j.request_type,
        j.service_name::text,
        j.service_description::text,
        j.service_street::text,
        j.service_barangay::text,
        j.job_status::text,
        j.agreed_price,
        j.payment_structure,
        j.requested_at,
        COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                       'offer_id', o.offer_id, 'offered_by', o.offered_by,
                       'amount', o.amount, 'note', o.note, 'created_at', o.created_at)
                   ORDER BY o.created_at, o.offer_id)
            FROM job_offers o WHERE o.job_id = j.job_id
        ), '[]'::jsonb)
    FROM job_requests j
    JOIN providers p  ON p.provider_id = j.provider_id
    JOIN users pu     ON pu.user_id    = p.user_id
    JOIN customers c  ON c.customer_id = j.customer_id
    JOIN users cu     ON cu.user_id    = c.user_id
    WHERE cu.auth_id = auth.uid()
    ORDER BY j.requested_at DESC;
$$;

ALTER FUNCTION "public"."get_customer_jobs"() OWNER TO "postgres";
REVOKE EXECUTE ON FUNCTION "public"."get_customer_jobs"() FROM PUBLIC, "anon";
GRANT  EXECUTE ON FUNCTION "public"."get_customer_jobs"() TO "authenticated";

CREATE OR REPLACE FUNCTION "public"."get_provider_jobs"()
RETURNS TABLE (
    "job_id"              bigint,
    "customer_name"       text,
    "request_type"        text,
    "service_name"        text,
    "service_description" text,
    "service_street"      text,
    "service_barangay"    text,
    "job_status"          text,
    "agreed_price"        numeric,
    "payment_structure"   text,
    "requested_at"        timestamptz,
    "offers"              jsonb
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET "search_path" = "public"
AS $$
    SELECT
        j.job_id,
        cu.full_name::text,
        j.request_type,
        j.service_name::text,
        j.service_description::text,
        j.service_street::text,
        j.service_barangay::text,
        j.job_status::text,
        j.agreed_price,
        j.payment_structure,
        j.requested_at,
        COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                       'offer_id', o.offer_id, 'offered_by', o.offered_by,
                       'amount', o.amount, 'note', o.note, 'created_at', o.created_at)
                   ORDER BY o.created_at, o.offer_id)
            FROM job_offers o WHERE o.job_id = j.job_id
        ), '[]'::jsonb)
    FROM job_requests j
    JOIN customers c  ON c.customer_id = j.customer_id
    JOIN users cu     ON cu.user_id    = c.user_id
    JOIN providers p  ON p.provider_id = j.provider_id
    JOIN users pu     ON pu.user_id    = p.user_id
    WHERE pu.auth_id = auth.uid()
    ORDER BY j.requested_at DESC;
$$;

ALTER FUNCTION "public"."get_provider_jobs"() OWNER TO "postgres";
REVOKE EXECUTE ON FUNCTION "public"."get_provider_jobs"() FROM PUBLIC, "anon";
GRANT  EXECUTE ON FUNCTION "public"."get_provider_jobs"() TO "authenticated";
